github: @DongDuong2001
patreon: DongDuong2001
ko_fi: dongphuduong
buy_me_a_coffee: lab68dev
custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=dongduong840@gmail.com&currency_code=USD']
